site_name: Simplenote

repo_name: 2023.1-Simplenote
repo_url: https://github.com/Requisitos-de-Software/2023.1-Simplenote
site_url: https://2023.1-Simplenote.com/

copyright: Copyright &copy; 2023 Simplenote

theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  language: pt-BR
  logo: img/Simplenote.png
  favicon: img/Simplenote-48.png

  features:
  - toc.integrate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer


  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: blue
    toggle:
      icon: material/weather-sunny
      name: Dark mode

  # Palette toggle for dark mode
  - scheme: slate
    primary: blue
    toggle:
      icon: material/weather-night
      name: Light mode

  font:
    text: "Montserrat"
    code: "sans-serif"

markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/Requisitos-de-Software/2023.1-Simplenote

nav:
  - Home: index.md
  - Atas: atas.md
  - Entregas: entregas.md
  - Elicitação:
    - Técnicas Planejadas:
      - StoryTelling: elicitacao/storytelling.md
      - Personas: elicitacao/personas.md
      - Questionário: elicitacao/questionario.md
      - Introspecção: elicitacao/Introspecção.md
      - Glossário: elicitacao/glossario.md
      - Entrevista: elicitacao/entrevista.md
      - Brainstorm: elicitacao/brainstorming.md
    - Priorização:
      - MosCoW: elicitacao/Priorização/MoScoW.md
      - First Things First (FTF): elicitacao/Priorização/FirstthingsFirst.md
      - Escala de Três Níveis: elicitacao/Priorização/ThreeLevelScale.md
      - Priorização final: elicitacao/Priorização/priorizacao_final.md
  - Modelagem:
    - Modelagem Ágil:
      - História de Usuário: modelagem/agil/User_story.md
      - Backlog: modelagem/agil/backlog.md
      - NFR: modelagem/nfr.md
    - Léxicos: modelagem/lexico.md
    - Cenários: modelagem/cenários.md
    - Casos de Uso: modelagem/casos_de_uso.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
  - Planejamento:
    - Cronograma pretendido: planejamento/cronograma.md
    - Cronograma realizado: planejamento/cronograma_realizado.md
    - Ferramentas: planejamento/ferramentas.md
    - Metodologias: planejamento/metodologias.md
    - Aplicativo Selecionado: planejamento/Aplicativo Selecionado.md
  - Elicitação:
    - Técnicas Planejadas:
      - StoryTelling: elicitacao/storytelling.md
      - Personas: elicitacao/personas.md
      - Questionário: elicitacao/questionario.md
      - Introspecção: elicitacao/Introspecção.md
      - Glossário: elicitacao/glossario.md
      - Entrevista: elicitacao/entrevista.md
      - Brainstorm: elicitacao/brainstorming.md
    - Priorização:
      - MosCoW: elicitacao/Priorização/MoScoW.md
      - First Things First (FTF): elicitacao/Priorização/FirstthingsFirst.md
      - Escala de Três Níveis: elicitacao/Priorização/ThreeLevelScale.md
      - Priorização final: elicitacao/Priorização/priorizacao_final.md
  - Modelagem:
    - Modelagem Ágil:
      - História de Usuário: modelagem/agil/User_story.md
      - Backlog: modelagem/agil/backlog.md
      - NFR: modelagem/nfr.md
    - Léxicos: modelagem/lexico.md
    - Cenários: modelagem/cenários.md
    - Casos de Uso: modelagem/casos_de_uso.md
    - Especificação Suplementar: modelagem/especificacao_suplementar.md
  - Pré-rastreabilidade:
    - Rich Picture: pré-rastreabilidade/rich_picture.md
    - Escolha do aplicativo: pré-rastreabilidade/escolha_rp.md
    - Aplicativo Selecionado: planejamento/Aplicativo Selecionado.md
  - Pós-rastreabilidade:
    - Forward-From: pos-rastreabilidade/Forward-From.md
    - Backward-From: pos-rastreabilidade/backward-from.md
    - Matriz: pos-rastreabilidade/matriz.md
  - Análises (V&V):
    - Verificação:      
      - Verificação - Simplenote:
        - Elicitação:
          - Técnicas Planejadas:
            - StoryTelling: analise/verificacao/verificacao-Grupo5/elicitacao/StoryTelling.md
            - Personas: analise/verificacao/verificacao-Grupo5/elicitacao/Personas.md
            - Questionário: analise/verificacao/verificacao-Grupo5/elicitacao/Questionário.md
            - Introspecção: analise/verificacao/verificacao-Grupo5/elicitacao/Introspecção.md
            - Glossário: analise/verificacao/verificacao-Grupo5/elicitacao/glossario.md
            - Entrevista: analise/verificacao/verificacao-Grupo5/elicitacao/entrevista.md
            - Brainstorm: analise/verificacao/verificacao-Grupo5/elicitacao/brainstorming.md
        - Priorização:
          - MosCoW: analise/verificacao/verificacao-Grupo5/elicitacao/priorização/moscow.md
          - First Things First (FTF): analise/verificacao/verificacao-Grupo5/elicitacao/priorização/FTF.md
          - Escala de Três Níveis: analise/verificacao/verificacao-Grupo5/elicitacao/priorização/TLS.md
        - Modelagem:
          - Modelagem Ágil:
            - História de Usuário: analise/verificacao/verificacao-Grupo5/modelagem/HistoriasDeUsuario.md
            - Backlog: analise/verificacao/verificacao-Grupo5/modelagem/backlog.md
            - NFR: analise/verificacao/verificacao-Grupo5/modelagem/nfr.md
          - Léxicos: analise/verificacao/verificacao-Grupo5/modelagem/lexicos.md
          - Cenários: analise/verificacao/verificacao-Grupo5/modelagem/Cenarios.md
          - Casos de Uso: analise/verificacao/verificacao-Grupo5/modelagem/CasosDeUso.md
          - Especificação Suplementar: analise/verificacao/verificacao-Grupo5/modelagem/especificacao_suplementar.md
        - Planejamento:
          - Cronograma pretendido: analise/verificacao/verificacao-Grupo5/planejamento/cronograma.md
          - Cronograma realizado: analise/verificacao/verificacao-Grupo5/planejamento/cronograma_realizado.md
          - Ferramentas: analise/verificacao/verificacao-Grupo5/planejamento/ferramentas.md
          - Metodologias: analise/verificacao/verificacao-Grupo5/planejamento/metodologias.md
          - Aplicativo Selecionado: analise/verificacao/verificacao-Grupo5/planejamento/app.md
          - Rich Picture: analise/verificacao/verificacao-Grupo5/planejamento/rich_picture.md 
      - Validação- Simplenote: 
        - Protótipo: analise/validacao/prototipo.md
        - Comprovação informal: analise/validacao/comprovacao_informal.md
      - Verificação - Grupo 6:
        - Verificação geral: analise/verificacao/verificacao-grupo6/verificacao_grupo6.md
        - Elicitação:
          - Perfil do usuário: analise/verificacao/verificacao-grupo6/elicitacao/PerfilDeUsuario.md
          - Análise de documento: analise/verificacao/verificacao-grupo6/elicitacao/analise_documentos.md
          - Entrevista: analise/verificacao/verificacao-grupo6/elicitacao/entrevista.md
          - Introspecção: analise/verificacao/verificacao-grupo6/elicitacao/instrospecção.md
          - Personas: analise/verificacao/verificacao-grupo6/elicitacao/personas.md
          - Priorização: analise/verificacao/verificacao-grupo6/elicitacao/priorizacao.md
          - Questionário: analise/verificacao/verificacao-grupo6/elicitacao/questionario.md
          - Priorização: analise/verificacao/verificacao-grupo6/elicitacao/priorizacao.md
          - Storytelling: analise/verificacao/verificacao-grupo6/elicitacao/storytelling.md
        - Modelagem:
          - Modelagem Ágil:
            - História de Usuário: analise/verificacao/verificacao-grupo6/modelagem/Agil/Historias_de_usuario.md
            - Backlog: analise/verificacao/verificacao-grupo6/modelagem/Agil/backlog.md
          - NFR: analise/verificacao/verificacao-grupo6/modelagem/NFR.md
          - Léxicos: analise/verificacao/verificacao-grupo6/modelagem/lexicos.md
          - Casos de Uso: analise/verificacao/verificacao-grupo6/modelagem/casos_de_uso.md
          - Cenários: analise/verificacao/verificacao-grupo6/modelagem/cenarios.md
          - Especificação Suplementar: analise/verificacao/verificacao-grupo6/modelagem/especificacao_suplementar.md
          - Léxicos: analise/verificacao/verificacao-grupo6/modelagem/lexicos.md
        - Planejamento:
          - Cronograma: analise/verificacao/verificacao-grupo6/planejamento/cronograma.md
          - Ferramentas: analise/verificacao/verificacao-grupo6/planejamento/ferramentas.md
          - Metodologias: analise/verificacao/verificacao-grupo6/planejamento/metodologia.md
          - Aplicativo Selecionado: analise/verificacao/verificacao-grupo6/planejamento/app.md
          - Rich Picture: analise/verificacao/verificacao-grupo6/planejamento/RichPicture.md
        - Extra:
          - GitPage: analise/verificacao/verificacao-grupo6/extras/gitpage.md
          - Atas: analise/verificacao/verificacao-grupo6/extras/atas.md
        - Template: analise/verificacao/verificacao-grupo6/template.md
  - Entrega Final: 
    - Documentação final: entrega-final.md
    - Post mortem: PostMortem.md
  

  


