site_name: Crunchyroll

repo_name: 2023.1-Crunchyroll
repo_url: https://github.com/Requisitos-de-Software/2023.1-Crunchyroll

copyright: Copyright &copy; 2023 Crunchyroll

theme:
  name: material
  language: pt
  logo: img/Crunchyroll.png
  favicon: img/Crunchyroll.png
   # Palette toggle for light mode
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Dark mode
# Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Light mode

  font:
    text: "Montserrat"
    code: "sans-serif"

  features:
    - navigation.tabs
    - navigation.section

nav: 
  - Home: index.md
  - Atas: atas.md
  - Elicitacao: elicitacao/personas.md
  - Planejamento: 
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologias: planejamento/metodologias.md
