site_name: Simplenote

repo_name: 2023.1-Simplenote
repo_url: https://github.com/Requisitos-de-Software/2023.1-Simplenote
site_url: https://2023.1-Simplenote.com/

copyright: Copyright &copy; 2023 Simplenote

theme:
  name: material
  language: pt-BR
  logo: img/Simplenote.png
  favicon: img/Simplenote-48.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
   
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Light mode

  font:
    text: "Montserrat"
    code: "sans-serif"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav: 
  - Home: index.md
  - Atas: atas.md
  - Entregas: entregas.md
  - Elicitação: elicitacao/personas.md
  - Planejamento: 
      - Cronograma pretendido: planejamento/cronograma.md
      - Cronograma realizado: planejamento/cronograma_realizado.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologias: planejamento/metodologias.md
      - Aplicativo Selecionado: planejamento/Aplicativo Selecionado.md
  - Pré-rastreabilidade:
      - Rich Picture: pré-rastreabilidade/rich_picture.md
