site_name: Simplenote

repo_name: 2023.1-Simplenote
repo_url: https://github.com/Requisitos-de-Software/2023.1-Simplenote
site_url: https://2023.1-Simplenote.com/

copyright: Copyright &copy; 2023 Simplenote

theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  language: pt-BR
  logo: img/Simplenote.png
  favicon: img/Simplenote-48.png

  features:
  - toc.integrate
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.footer


  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: blue
    toggle:
      icon: material/weather-sunny
      name: Dark mode

  # Palette toggle for dark mode
  - scheme: slate
    primary: blue
    toggle:
      icon: material/weather-night
      name: Light mode

  font:
    text: "Montserrat"
    code: "sans-serif"

markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/Requisitos-de-Software/2023.1-Simplenote

nav:
- Home: index.md
- Atas: atas.md
- Entregas: entregas.md
- Elicitação:
  - Técnicas Planejadas:
    - StoryTelling: elicitacao/storytelling.md
    - Personas: elicitacao/personas.md
    - Questionário: elicitacao/questionario.md
    - Introspecção: elicitacao/Introspecção.md
    - Glossário: elicitacao/glossario.md
    - Entrevista: elicitacao/entrevista.md
    - Brainstorm: elicitacao/brainstorming.md

  - Priorização:
    - MosCoW: elicitacao/Priorização/MoScoW.md
    - First Things First (FTF): elicitacao/Priorização/FirstthingsFirst.md
    - Escala de Três Níveis: elicitacao/Priorização/ThreeLevelScale.md
    - Priorização final: elicitacao/Priorização/priorizacao_final.md

- Modelagem:
  - Modelagem Ágil:
    - História de Usuário: modelagem/agil/User_story.md
    - Backlog: modelagem/agil/backlog.md
    - NFR: modelagem/nfr.md
  - Léxicos: modelagem/lexico.md
  - Cenários: modelagem/cenários.md
  - Casos de Uso: modelagem/casos_de_uso.md
  - Especificação Suplementar: modelagem/especificacao_suplementar.md

- Alálise (V&V):
  - Verificação Grupo 6:
    - Verificação geral: analise-grupo6/verificacao_grupo6.md
    - Elicitação:
      #- Personas: analise-grupo6/elicitacao/personas.md
      #- Questionário: analise-grupo6/elicitacao/questionario.md
      #- Introspecção: analise-grupo6/elicitacao/Introspecção.md
      #- Glossário: analise-grupo6/elicitacao/glossario.md
      - Entrevista: analise-grupo6/elicitacao/entrevista.md
      #- Brainstorm: analise-grupo6/elicitacao/brainstorming.md
      - Priorização: analise-grupo6/elicitacao/priorizacao.md

    - Modelagem:
      - Modelagem Ágil:
        - História de Usuário: analise-grupo6/modelagem/Agil/Historias_de_usuario.md
        - Backlog: analise-grupo6/modelagem/Agil/backlog.md
        - NFR: analise-grupo6/modelagem/nfr.md
      - Léxicos: analise-grupo6/modelagem/lexicos.md
      #- Cenários: analise-grupo6/modelagem/cenários.md
      #- Casos de Uso: analise-grupo6/modelagem/casos_de_uso.md
      - Especificação Suplementar: analise-grupo6/modelagem/especificacao_suplementar.md
    - Planejamento:
      - Cronograma: analise-grupo6/planejamento/cronograma.md
      - Ferramentas: analise-grupo6/planejamento/ferramentas.md
        #- Metodologias: analise-grupo6/planejamento/metodologias.md
        #- Aplicativo Selecionado: analise-grupo6/planejamento/Aplicativo Selecionado.md
    - Extra:
      - GitPage: analise-grupo6/extras/gitpage.md
      - Atas: analise-grupo6/extras/atas.md
      
#- Verificação Simplenote:


- Planejamento:
  - Cronograma pretendido: planejamento/cronograma.md
  - Cronograma realizado: planejamento/cronograma_realizado.md
  - Ferramentas: planejamento/ferramentas.md
  - Metodologias: planejamento/metodologias.md
  - Aplicativo Selecionado: planejamento/Aplicativo Selecionado.md

- Pré-rastreabilidade:
  - Rich Picture: pré-rastreabilidade/rich_picture.md
  - Escolha do aplicativo: pré-rastreabilidade/escolha_rp.md
